#ifdef CHERRYSODA_ENABLE_PROFILE

// Tracy Profiler
#ifdef CHERRYSODA_USE_TRACY_PROFILER
#	include <tracy/TracyClient.cpp>
#endif // CHERRYSODA_USE_TRACY_PROFILER

#endif // CHERRYSODA_ENABLE_PROFILE
