#!/bin/bash

ENGINE_PATH=`dirname $0`/..
BGFX_PATH=External/bgfx/bgfx/src
INCLUDE_PATH=$ENGINE_PATH/$BGFX_PATH
SC=shaderc
$SC -f $1/fs_$2.sc -o $1/fs_$2.bin --platform linux --type fragment -i $INCLUDE_PATH --profile 120
$SC -f $1/vs_$2.sc -o $1/vs_$2.bin --platform linux --type vetex -i $INCLUDE_PATH --profile 120
$SC -f $1/fs_$2.sc -o $1/fs_$2.esl.bin --platform nacl --type fragment -i $INCLUDE_PATH
$SC -f $1/vs_$2.sc -o $1/vs_$2.esl.bin --platform nacl --type vetex -i $INCLUDE_PATH
$SC -f $1/fs_$2.sc -o $1/fs_$2.and.bin --platform android --type fragment -i $INCLUDE_PATH
$SC -f $1/vs_$2.sc -o $1/vs_$2.and.bin --platform android --type vetex -i $INCLUDE_PATH
